Skip to content
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
visa php
Repositories42
Code1M
Commits1K
Issues978
Marketplace0
Topics0
Wikis431
Users2
Language

Sort

php logo
PHP
PHP is a popular general-purpose scripting language that works particularly well for server-side web development.

See topic
42 repository results
AuthorizeNet/sdk-php
PHP SDK for Authorize.Net API
sdk-php
php
payment
payments
payment-methods
authorizenet
visa
payment-gateway
payment-integration
payment-processing
payment-service
payment-module
merchants
merchant
Updated 21 days ago

 PHP
 279
CyberSource/cybersource-sdk-php
PHP SDK for Cybersource SOAP Toolkit API
php-client
php
sdk-php
cybersource
payment
payments
payment-methods
soap-api
visa
payment-gateway
payment-integration
payment-processing
payment-request
payment-service
payment-module
merchants
Updated on Apr 10, 2017

 PHP
 31
tetrahydra/SolidusMRZ
PHP Parse MRZ from Passport, Visa or ID-1
GPL-3.0 license

Updated on Jul 14, 2018

 PHP
 1
tapajos/php-pagamento
Estrutura para e-commerce com Visa e Mastercard em PHP.
Updated on Jun 16, 2008

 PHP
 13
PayEx/PayEx.WooCommerce
PayEx Payment Provider for WooCommerce
payex
php
payment-gateway
ecommerce
woocommerce
visa
legacy
soap
Updated on Oct 3, 2018

 PHP
 4
stratedge/visa
A complimentary extension of the official Laravel Passport package.
passport
laravel
php
oauth2
php7
laravel-5-package
laravel-passport
MIT license

Updated on Dec 2, 2018

 PHP
 2
andersonlarcher/SistemaDeTrocasDW3
Sistema de trocas web em PHP. O sistema visa trocar qualquer coisa que seja do gosto do usuário.
Updated on May 13, 2014

 PHP
PHPSPSantos/how-to
Dedicado à iniciativa que visa ajudar àqueles(as) que querem aprender a trabalhar com PHP e seu ecossistema do jeito …
Updated on May 5, 2018

 PHP
 3
jmanuelemus/VisaNet
A PHP package to perform online payments through VisaNet Guatemala
php
Updated on May 16, 2018

 PHP
IgorDePaula/StatePattern
Este repo visa o ensino do State Pattern em PHP
php
design-patterns
state-pattern
Updated on Oct 4, 2017

 HTML
 2
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
